"""Seed flow stages and resources into the database (idempotent)."""
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from .models import FlowStage, FlowStageResource


def _flow_stages_data():
    """Return all flow stage definitions. Each is (stage_key, flow_type, sort_order, title, days, desc, resources).
    resources is list of (title, resource_type, sort_order)."""
    new_stages = [
        ("design", "new", 1, "设计与开工准备", "7-15天",
         "先完成收房验房，检查墙面开裂、空鼓等问题并及时要求开发商整改；再通过上门量房，沟通设计风格、平面布局与水电点位；最后携带身份证、房产证、施工图到物业办理装修许可证，缴纳装修保证金，并确认墙体拆改限制、门窗封装要求、垃圾清运等事项。",
         [("毛坯房验收", "acceptance", 1),
          ("量房步骤", "article", 2),
          ("自装第一步，物业报备超详细流程", "article", 3),
          ("选择装修公司的核心要点", "article", 4)]),
        ("demolish", "new", 2, "墙体拆改", "2-4天",
         "墙体拆改是优化户型布局的重要环节，主要包括非承重墙拆除、门洞调整及局部结构改造。施工前必须核对图纸并确认承重墙、梁柱、烟道及公共管线位置，严禁破坏主体结构。",
         [("墙体拆改施工规范", "standard", 1),
          ("墙体拆改标准化验收", "acceptance", 2)]),
        ("wall-new", "new", 3, "新建墙体", "2-3天",
         "新建墙体是空间结构改造的核心环节，从定位放线、砂浆配比到植筋拉结、顶部斜砌，每一道工序都会影响墙体的稳固性、垂直度及后期抗裂性能。",
         [("新建墙体施工规范", "standard", 1),
          ("新建墙体标准化验收", "acceptance", 2)]),
        ("window", "new", 4, "门窗封装施工", "1-3天",
         "选断桥铝材质隔音隔热，测量后工厂定制周期约7-15天，安装时打胶要饱满，窗边缝隙用发泡胶填充防渗水。",
         [("门窗封装施工规范", "standard", 1),
          ("门窗封装标准化验收", "acceptance", 2),
          ("门窗选购与封装攻略", "article", 3)]),
        ("electric", "new", 5, "水电改造", "5-10天",
         "根据生活习惯定位插座、开关、水口，厨卫水电走顶更易检修，完工后做48小时水路打压测试，0.8MPa不掉压为合格。",
         [("电路施工规范", "standard", 1),
          ("水路施工规范", "standard", 2),
          ("水电材料进场验收", "acceptance", 3),
          ("电路标准化验收", "acceptance", 4),
          ("水路标准化验收", "acceptance", 5),
          ("水电走地 vs 走顶", "article", 6),
          ("电路安装工艺", "article", 7),
          ("强弱电知识", "article", 8),
          ("水管选购", "article", 9)]),
        ("pipe-sound", "new", 6, "管道隔音施工", "1-2天",
         "针对厨房下水管、卫生间立管做隔音处理，先用隔音棉包裹管道，再缠扎带固定，减少水流噪音，尤其适合高层住户。",
         [("管道隔音施工规范", "standard", 1),
          ("管道隔音标准化验收", "acceptance", 2)]),
        ("waterproof", "new", 7, "防水施工", "2-3天",
         "卫生间刷至1.8米高，厨房刷30cm高，淋浴区做满墙；用柔性防水涂料，横竖交叉涂刷2-3遍，墙角阴角做圆弧处理防开裂。",
         [("防水施工规范", "standard", 1),
          ("防水标准化验收", "acceptance", 2),
          ("防水材料解析", "article", 3),
          ("下沉式卫生间回填", "article", 4)]),
        ("tile", "new", 8, "墙地砖铺贴", "5-7天",
         "地面先找平，瓷砖提前泡水2小时；厨卫墙地对缝铺贴，留2-3mm缝方便美缝；铺贴后24小时内禁踩，72小时后检查空鼓，空鼓率不超过5%。",
         [("墙地砖铺贴施工交底", "standard", 1),
          ("墙砖铺贴施工规范", "standard", 2),
          ("地砖铺贴施工规范", "standard", 3),
          ("铺地砖标准化验收", "acceptance", 4),
          ("铺墙砖标准化验收", "acceptance", 5),
          ("瓷砖购买指南", "article", 6),
          ("瓷砖的选择与建议", "article", 7)]),
        ("grout", "new", 9, "瓷砖美缝", "1-2天",
         "瓷砖铺贴1周后做美缝，先清缝再打胶，用刮板压平后24小时固化；推荐选环氧彩砂，防水防霉适合厨卫。",
         [("瓷砖美缝施工规范", "standard", 1),
          ("瓷砖美缝标准化验收", "acceptance", 2),
          ("美缝材料分类及适用场景说明", "article", 3)]),
        ("protect", "new", 10, "成品保护", "1天",
         "用1.2mm厚地膜满铺地面，接缝处用胶带粘牢，覆盖墙面30cm高，防止后续施工刮花瓷砖。",
         [("地面成品保护全流程", "standard", 1)]),
        ("ceiling", "new", 11, "木工吊顶", "3-5天",
         "客餐厅用轻钢龙骨加石膏板，防潮款适合潮湿区；厨卫装铝扣板，方便检修；预留灯具、浴霸、排气扇位置。",
         [("木工吊顶施工交底", "standard", 1),
          ("木工吊顶施工规范", "standard", 2),
          ("木工吊顶标准化验收", "acceptance", 3),
          ("自装吊顶龙骨+面板选购", "article", 4),
          ("6种主流吊顶类型详解", "article", 5)]),
        ("wall-base", "new", 12, "墙面基层处理", "3-5天",
         "墙面先刷界面剂，腻子每遍薄刮，厚度不超过2mm，干透后用砂纸打磨平整；阴角、阳角需用靠尺找直。",
         [("墙面基层处理施工规范", "standard", 1),
          ("墙面基层处理标准化验收", "acceptance", 2)]),
        ("paint", "new", 13, "墙面涂饰", "2-3天",
         "先刷抗碱底漆封闭基层，再刷两遍面漆；每遍间隔4-6小时，温度低于5℃需停止施工，避免漆膜开裂。",
         [("墙面涂饰施工规范", "standard", 1),
          ("墙面涂饰标准化验收", "acceptance", 2)]),
        ("door", "new", 14, "室内门安装", "1-2天",
         "提前与地板预留5-8mm伸缩缝，门套与墙面缝隙用发泡胶填充，外沿打美容胶收边；实木门需做防潮处理。",
         [("室内门安装施工规范", "standard", 1),
          ("室内门安装标准化验收", "acceptance", 2),
          ("木门选购指南", "article", 3)]),
        ("kitchen", "new", 15, "厨房电器安装", "1天",
         "与橱柜同步测量尺寸，烟管尽量短且少拐弯；安装后检查止逆阀密封性，避免油烟倒灌。",
         [("油烟机选购要点", "article", 1)]),
        ("custom-wood", "new", 16, "全屋定制安装", "1-2天",
         "定制周期约30-45天，安装时先固定柜体再装门板；检查门缝均匀度，五金件调试顺滑度。",
         [("家装板材全解析与选择", "article", 1),
          ("主流饰面类型解析与选择", "article", 2)]),
        ("baseboard", "new", 17, "踢脚线安装", "1-2天",
         "瓷砖踢脚线用水泥粘贴，木质踢脚线打钉固定；与墙面缝隙用美缝剂填充，拐角处45°拼接更美观。",
         [("踢脚线材质选择", "article", 1)]),
        ("light", "new", 18, "灯具及开关安装", "1-2天",
         "吊灯需提前预埋承重挂钩，承重为灯具重量的25倍；筒灯、射灯开孔尺寸与灯具匹配，避免过大留缝。",
         [("简约风无主灯布局攻略", "article", 1)]),
        ("bath", "new", 19, "卫浴洁具安装", "1-2天",
         "马桶安装先做防水密封圈，浴室柜与墙面打玻璃胶；花洒冷热水管间距15cm，高度1.1m。",
         [("卫浴选购指南", "article", 1)]),
        ("clean", "new", 20, "开荒保洁", "1-2天",
         "用铲刀清理瓷砖水泥渍，玻璃刮去除窗膜，高温蒸汽清洁缝隙；重点清理胶印、粉尘和建筑垃圾。",
         [("新房开荒工具清单", "article", 1),
          ("新房开荒步骤详解", "article", 2)]),
        ("curtain", "new", 21, "窗帘安装", "1天",
         "轨道安装距顶5-10cm显层高，窗帘杆两端预留20cm延伸量；挂钩式窗帘需均匀间距，确保垂坠感。",
         [("窗帘主流面料选择", "article", 1),
          ("8款热门纱帘全解析", "article", 2),
          ("罗马杆 vs 顶装轨道 vs 窗帘盒", "article", 3)]),
        ("furniture", "new", 22, "家具软装进场", "1-3天",
         "先进衣柜、沙发等大件，再摆茶几、床头柜；实木家具避免阳光直射，皮质家具先通风散味。",
         []),
    ]

    old_stages = [
        ("old-inspect", "old", 1, "验房评估", "3-5天",
         "检查旧房现状：墙面、地面、水电管线、门窗等，确定改造范围和预算。重点检查水电管线老化程度。", []),
        ("old-demolish", "old", 2, "拆除旧物", "3-7天",
         "拆除旧装修：地板、瓷砖、吊顶、旧柜子、旧门窗等。注意保护承重结构。",
         [("墙体拆除施工规范", "standard", 1),
          ("墙体拆除标准化验收", "acceptance", 2)]),
        ("old-repair", "old", 3, "结构修补", "2-5天",
         "修补拆除后的墙体、地面，处理裂缝和空鼓。必要时加固结构。空鼓必须处理，否则后期贴砖会掉。", []),
        ("old-electric", "old", 4, "水电改造", "5-10天",
         "旧房水电一般需要全部重新铺设。老房子铝线要换铜线，水管建议换PPR管。",
         [("电路施工规范", "standard", 1),
          ("水路施工规范", "standard", 2),
          ("水电材料进场验收", "acceptance", 3),
          ("电路标准化验收", "acceptance", 4),
          ("水路标准化验收", "acceptance", 5),
          ("水电走地 vs 走顶", "article", 6),
          ("电路安装工艺", "article", 7)]),
        ("old-waterproof", "old", 5, "防水施工", "3-5天",
         "重新做防水，特别是卫生间和厨房。旧房防水层可能已经失效。",
         [("防水施工规范", "standard", 1),
          ("防水标准化验收", "acceptance", 2),
          ("防水材料解析", "article", 3)]),
        ("old-tile", "old", 6, "瓦工贴砖", "10-15天",
         "重新铺设墙地砖。旧房可能需要先做地面找平再贴砖。",
         [("铺砖施工交底", "standard", 1),
          ("铺墙砖施工规范", "standard", 2),
          ("铺地砖施工规范", "standard", 3),
          ("铺地砖标准化验收", "acceptance", 4),
          ("铺墙砖标准化验收", "acceptance", 5),
          ("瓷砖购买指南", "article", 6),
          ("瓷砖的选择与建议", "article", 7)]),
        ("old-wood", "old", 7, "木工油漆", "15-25天",
         "吊顶、墙面处理、刷漆。旧墙需要铲到红砖重新刮腻子。有裂缝处要贴网格布防裂。",
         [("吊顶施工规范", "standard", 1),
          ("刮腻子施工规范", "standard", 2),
          ("刷漆施工规范", "standard", 3),
          ("吊顶标准化验收", "acceptance", 4),
          ("刮腻子标准化验收", "acceptance", 5),
          ("刷漆标准化验收", "acceptance", 6),
          ("自装吊顶龙骨+面板选购", "article", 7),
          ("6种主流吊顶类型详解", "article", 8)]),
        ("old-install", "old", 8, "安装阶段", "15-20天",
         "橱柜、木门、地板、卫浴、灯具、开关面板等安装。旧门窗建议更换。",
         [("安门施工规范", "standard", 1),
          ("安门标准化验收", "acceptance", 2),
          ("木门选购指南", "article", 3),
          ("卫浴选购指南", "article", 4)]),
        ("old-ventilate", "old", 9, "通风入住", "30-60天",
         "通风散味。旧房翻新用料相对少，通风时间可适当缩短，建议至少通风1个月再入住。", []),
    ]

    return new_stages + old_stages


async def seed_flow_stages(db: AsyncSession):
    """Seed flow stages and resources (idempotent — skips if stages exist)."""
    existing = await db.execute(select(FlowStage).limit(1))
    if existing.scalar_one_or_none():
        return  # Already seeded

    for stage_key, flow_type, order, title, days, desc, resources in _flow_stages_data():
        stage = FlowStage(
            stage_key=stage_key,
            flow_type=flow_type,
            sort_order=order,
            title=title,
            days=days,
            desc=desc,
        )
        db.add(stage)
        await db.flush()  # get stage.id

        for r_title, r_type, r_order in resources:
            db.add(FlowStageResource(
                stage_id=stage.id,
                title=r_title,
                resource_type=r_type,
                sort_order=r_order,
            ))

    await db.commit()
